{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "32badbdd",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import akshare as ak\n",
    "from datetime import datetime\n",
    "import os\n",
    "\n",
    "# 统一保存路径（保持与 fetch_all_main.py 一致）\n",
    "SAVE_PATH = \"/content/drive/MyDrive/quantitiave interest/data\"\n",
    "\n",
    "# 加载本地数据并判断最新日期\n",
    "def load_existing_data(file_path: str) -> pd.DataFrame:\n",
    "    if os.path.exists(file_path):\n",
    "        df = pd.read_csv(file_path, encoding=\"utf-8-sig\", parse_dates=[\"date\"])\n",
    "        print(f\"📂 已加载历史数据：{file_path}（至 {df['date'].max().date()}）\")\n",
    "        return df\n",
    "    else:\n",
    "        print(f\"⚠️ 未找到历史数据文件，将初始化抓取：{file_path}\")\n",
    "        return pd.DataFrame()\n",
    "\n",
    "# 从 akshare 获取新数据\n",
    "def fetch_latest_main(symbol: str, name: str) -> pd.DataFrame:\n",
    "    df = ak.futures_zh_daily_sina(symbol=symbol)\n",
    "    df[\"date\"] = pd.to_datetime(df[\"date\"])\n",
    "    df[\"symbol\"] = name\n",
    "    return df[[\"symbol\", \"date\", \"open\", \"high\", \"low\", \"close\", \"volume\"]]\n",
    "\n",
    "# 执行单个合约的数据更新逻辑\n",
    "def update_main_contract(symbol: str, name: str):\n",
    "    file_path = os.path.join(SAVE_PATH, f\"{name}_主连_国债期货.csv\")\n",
    "    existing = load_existing_data(file_path)\n",
    "    latest = fetch_latest_main(symbol, name)\n",
    "\n",
    "    if not existing.empty:\n",
    "        latest = latest[latest[\"date\"] > existing[\"date\"].max()]\n",
    "\n",
    "    if latest.empty:\n",
    "        print(f\"✅ {name} 无需更新，数据已是最新。\")\n",
    "    else:\n",
    "        updated = pd.concat([existing, latest], ignore_index=True).drop_duplicates(subset=\"date\").sort_values(\"date\")\n",
    "        updated.to_csv(file_path, index=False, encoding=\"utf-8-sig\")\n",
    "        print(f\"✅ {name} 已更新 {len(latest)} 条数据 → 共 {len(updated)} 条记录\")\n",
    "\n",
    "# 合约映射\n",
    "contracts = {\n",
    "    \"TS0\": \"TS_2Y\",\n",
    "    \"TF0\": \"TF_5Y\",\n",
    "    \"T0\": \"T_10Y\",\n",
    "    \"TL0\": \"TL_30Y\"\n",
    "}\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    for symbol, name in contracts.items():\n",
    "        print(f\"\\n🔄 正在更新：{name} 主连数据...\")\n",
    "        update_main_contract(symbol, name)\n",
    "    print(\"\\n✅ 所有合约数据更新完成！\")"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
